// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/unorm/unorm.d.ts
declare namespace unorm {
  interface Static {
    nfd(str: string): string;
    nfkd(str: string): string;
    nfc(str: string): string;
    nfkc(str: string): string;
  }
}

declare var unorm: unorm.Static;

declare module "unorm" {
  export = unorm;
}
